# базовые
background  #0e0e0f
foreground  #e6e6e6

# серые
color0      #1a1a1a
color8      #4a4a4a

# белые
color7      #dcdcdc
color15     #ffffff

# графит
selection_background #3a3a3a
selection_foreground #ffffff

cursor      #bfbfbf
cursor_text_color #000000

color1 #8a8a8a
color2 #9a9a9a
color3 #aaaaaa
color4 #b0b0b0
color5 #b8b8b8
color6 #c0c0c0

color9  #8a8a8a
color10 #9a9a9a
color11 #aaaaaa
color12 #b0b0b0
color13 #b8b8b8
color14 #c0c0c0

confirm_os_window_close 0
